name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipywidgets>=8.1.8,<9
  - nbformat>=5.10.4,<6

  # Scientific computing & data analysis
  - numpy>=1.0,<2
  - pandas>=1.5.3,<3
  - matplotlib>=3.8.4,<4
  - scipy>=1.11.1,<2
  - scikit-learn>=1.1.1,<2
  - plotly>=6.5.0,<7
  - seaborn>=0.13.2,<0.14
  - folium>=0.20.0,<0.21

  # Data processing & utilities
  - requests>=2.32.5,<3
  - tqdm>=4.67.1,<5
  - toolz>=1.1.0,<2
  - arrow>=1.4.0,<2
  - openpyxl>=3.0.9,<4

  # Schema & validation
  - jsonschema>=4.17.3,<5
  - pydantic>=2.8.2,<3
  - marshmallow>=3.26.1,<4
  - param>=2.3.0,<3
  - beartype>=0.22.6,<0.23

  # CLI & UX
  - rich>=14.2.0,<15
  #- click>=8.3.1,<9
  #- typer>=0.20.0,<0.21

  # Data formats & serialization
  - json5>=0.12.1,<0.13
  - orjson>=3.10.6,<4
  - pyaml>=25.7.0,<26
  - pytz>=2025.2,<2026
  - beautifulsoup4>=4.14.2,<5

  # System & performance
  - deepdiff>=8.6.1,<9
  - pathspec>=0.12.1,<0.13
  - tenacity>=9.1.2,<10

  # Math & optimization
  - swiglpk>=5.0.10,<6
  - optlang>=1.8.2,<2
  - pygad>=3.5.0,<4
  - autograd>=1.8.0,<2

  # SQL & query
  - sqlglot>=28.0.0,<29
  - jinja2>=3.1.6,<4

  # storage / arrays / misc
  - awkward-cpp>=35,<36
  - boost-histogram>=1.4.1,<2
  - brotli>=1.1.0,<2
  - cffi>=1.15.1,<2
  - cftime>=1.6.2,<2
  - cryptography>=42.0.2,<43
  - docutils>=0.18.1,<0.19
  - fonttools>=4.39.4,<5
  - future>=1.0.0,<2
  #- ipython>=9.0.2,<10
  - joblib>=1.4.0,<2
  - kiwisolver>=1.3.2,<2
  - logbook>=1.6.0,<2
  - lxml>=4.9.4,<5
  - markupsafe>=3.0.2,<4
  - patsy>=1.0.1,<2
  - peewee>=3.17.3,<4
  - pillow>=10.3.0,<11
  - protobuf>=4.22.3,<5
  - pyproj>=3.7.1,<4
  - pyrsistent>=0.18.1,<0.19
  - pytest>=8.3.2,<9
  - pywavelets>=1.4.1,<2
  - pyyaml>=6.0,<7
  - regex>=2022.1.18,<2023
  - setuptools>=80.9.0,<81
  - sqlalchemy>=2.0.32,<3
  - statsmodels>=0.14.1,<0.15
  - sympy>=1.14.0,<2
  - traits>=7.0.2,<8
  - wrapt>=1.17.2,<2
  - zarr>=2.10.3,<3
  - diskcache>=5.6.3,<6
  - aiohttp>=3.13.2,<4
  - jupytext>=1.18.1,<2
  - altair>=6.0.0,<7
  - networkx>=3.2,<4
  - simpy>=4.1.1,<5
  - pandera>=0.22.1,<0.23
